api:
  - src/api/**/*

gill:
  - src/api/gill/**/*

component:
  - src/component/**/*

model:
  - src/models/*

redux:
  - src/actions/**/*
  - src/reducer/**/*
  - src/store/**/*

tests:
  - tests/**/*

structure:
  - ./*
  - public/**/*
  - config/**/*
  - config/*
  - config/**
  - public/**/*
  - scripts/**/*

doc:
  - ./*.md

bug:
  - ./**
